/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "ADD_PLACE": {                                   "en": "Add place",                                       "de": "Ort hinzufügen",                                  "ru": "Добавить место",                                  "pt": "Adicionar lugar",                                 "nl": "Voeg een plaats toe",                             "fr": "Ajouter un lieu",                                 "it": "Aggiungi posto",                                  "es": "Añadir lugar",                                    "pl": "Dodaj miejsce"},
    "GENERAL": {                                     "en": "General",                                         "de": "Allgemein",                                       "ru": "Генеральная",                                     "pt": "Geral",                                           "nl": "Algemeen",                                        "fr": "Général",                                         "it": "Generale",                                        "es": "General",                                         "pl": "Generał"},
    "HOME_NAME": {                                   "en": "Name of place if somebody is at home",            "de": "Name des Ortes, wenn jemand zu Hause ist",        "ru": "Название места, если кто-то дома",                "pt": "Nome do lugar se alguém estiver em casa",         "nl": "Naam van de plaats als iemand thuis is",          "fr": "Nom du lieu si quelqu'un est à la maison",        "it": "Nome del luogo se qualcuno è a casa",             "es": "Nombre del lugar si alguien está en casa",        "pl": "Nazwa miejsca, w którym ktoś jest w domu"},
    "PLACES": {                                      "en": "Places",                                          "de": "Orte",                                            "ru": "Пользовательские места",                          "pt": "Lugares personalizados",                          "nl": "Aangepaste plaatsen",                             "fr": "Lieux personnalisés",                             "it": "Posti personalizzati",                            "es": "Lugares personalizados",                          "pl": "Niestandardowe miejsca"},
    "PLACE_LATITUDE": {                              "en": "Latitude",                                        "de": "Breitengrad",                                     "ru": "широта",                                          "pt": "Latitude",                                        "nl": "Breedtegraad",                                    "fr": "Latitude",                                        "it": "Latitudine",                                      "es": "Latitud",                                         "pl": "Szerokość"},
    "PLACE_LONGITUDE": {                             "en": "Longitude",                                       "de": "Längengrad",                                      "ru": "долгота",                                         "pt": "Longitude",                                       "nl": "Lengtegraad",                                     "fr": "Longitude",                                       "it": "Longitudine",                                     "es": "Longitud",                                        "pl": "Długość geograficzna"},
    "PLACE_NAME": {                                  "en": "Name",                                            "de": "Name",                                            "ru": "имя",                                             "pt": "Nome",                                            "nl": "Naam",                                            "fr": "prénom",                                          "it": "Nome",                                            "es": "Nombre",                                          "pl": "Nazwa"},
    "PLACE_RADIUS": {                                "en": "Radius",                                          "de": "Radius",                                          "ru": "Радиус",                                          "pt": "Raio",                                            "nl": "Radius",                                          "fr": "Rayon",                                           "it": "Raggio",                                          "es": "Radio",                                           "pl": "Promień"},
    "RADIUS": {                                      "en": "Radius in meters used to find the current location", "de": "Radius in Metern zum Auffinden des aktuellen Orts", "ru": "Радиус в метрах, используемый для нахождения текущего местоположения", "pt": "Raio em metros usado para encontrar a localização atual", "nl": "Straal in meters gebruikt om de huidige locatie te vinden", "fr": "Rayon en mètres utilisé pour trouver l'emplacement actuel", "it": "Raggio in metri utilizzato per trovare la posizione corrente", "es": "Radio en metros utilizado para encontrar la ubicación actual", "pl": "Promień w metrach służy do znalezienia aktualnej lokalizacji"},
    "USERS": {                                       "en": "User",                                            "de": "Benutzer",                                        "ru": "User",                                            "pt": "User",                                            "nl": "User",                                            "fr": "User",                                            "it": "User",                                            "es": "User",                                            "pl": "User"},
    "USER_NAME": {                                   "en": "Username",                                        "de": "Benutzername",                                    "ru": "имя пользователя",                                "pt": "Nome de usuário",                                 "nl": "Gebruikersnaam",                                  "fr": "Nom d'utilisateur",                               "it": "Nome utente",                                     "es": "Nombre de usuario",                               "pl": "Nazwa Użytkownika"},
    "USER_REPLACEMENT": {                            "en": "Replace with",                                    "de": "Ersetzen durch",                                  "ru": "Заменить",                                        "pt": "Substituir com",                                  "nl": "Vervangen door",                                  "fr": "Remplacer par",                                   "it": "Sostituirlo con",                                 "es": "Reemplazar con",                                  "pl": "Zamienić"},
};